services:
  proxy:
    platform: linux/amd64
    image: jitolabs/jito-shredstream-proxy
    command: shredstream
    environment:
      - RUST_LOG=info
      - BLOCK_ENGINE_URL=https://ny.mainnet.block-engine.jito.wtf
      - AUTH_KEYPAIR=auth.json
      - DESIRED_REGIONS=ny
      - DEST_IP_PORTS=0.0.0.0:8001
    volumes:
      - ./auth.json:/app/auth.json
    network_mode: host

  shreds:
    image: mtfuji25/shreds
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shreds
    command: ["./shreds", "all"]
    volumes:
      - type: bind
        source: ./raydium.json
        target: /raydium.json
      - type: bind
        source: ./shreds.log
        target: /shreds.log
      - .env:/.env
      - ./FAST.json:/FAST.json
      - ./tokens.json:/tokens.json
    #ports:
    #  - "8001:8001/udp"
    network_mode: host

  cli:
    image: mtfuji25/shreds
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./raydium.json
        target: /raydium.json
      - type: bind
        source: ./shreds.log
        target: /shreds.log
      - type: bind
        source: ./packets.json
        target: /packets.json
      - .env:/.env
      - ./FAST.json:/FAST.json
    command: ["./shreds", "--help"]
    ports:
      - "8001:8001/udp"
